version: '3.9'
services:
    api:
        build:
            dockerfile: Dockerfile
            context: .
        restart: always    
        depends_on:
            - postgres
        environment:
            DATABASE_URL: postgres://postgres:Sourav6803@@postgres:5432/fuzonmedia
            NODE_ENV: development
            PORT: 5000
        ports: 
            - "5000:5000" 
        networks:
            - mynetwork 

    postgres:
        image: postgres:latest
        restart: always 
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: Sourav6803@
            POSTGRES_DB: fuzonmedia
        networks:
            - mynetwork

networks:
    mynetwork:
        driver: bridge